{
	"Name":"Classic",
	"Set":{
		"Start":[
			"nzu/round/classic/start/round_start.mp3"
		],
		"GameOver":[
			"nzu/round/classic/gameover/game_over_derriese.mp3"
		],
		"End":[
			"nzu/round/classic/end/round_end.mp3"
		]
	}
}